### ISSUE TITLE
Calibration app does not work on one phone but works on other

### ISSUE THREAD

**Issue by cpepi001** [DP-3T/dp3t-sdk-android#65]
Branch: master-alpha

When I try to run the Calibration app on a `X` phone the app crashes giving the error below but when I run the app on a `Y` phone the app does not crashes. Both phones run Android 7.0 and connected to the internet.

```
E/SQLiteLog: (1) no such table: matched_contacts
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.dpppt.android.calibration, PID: 2337
    java.lang.RuntimeException: Unable to resume activity {org.dpppt.android.calibration/org.dpppt.android.calibration.MainActivity}: android.database.sqlite.SQLiteException: no such table: matched_contacts (code 1): , while compiling: SELECT id, report_date, known_case_id FROM matched_contacts ORDER BY id
    #################################################################
    Error Code : 1 (SQLITE_ERROR)
    Caused By : SQL(query) error or missing database.
    	(no such table: matched_contacts (code 1): , while compiling: SELECT id, report_date, known_case_id FROM matched_contacts ORDER BY id)
    #################################################################
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3791)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3832)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2994)
        at android.app.ActivityThread.-wrap14(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
     Caused by: android.database.sqlite.SQLiteException: no such table: matched_contacts (code 1): , while compiling: SELECT id, report_date, known_case_id FROM matched_contacts ORDER BY id
    #################################################################
    Error Code : 1 (SQLITE_ERROR)
    Caused By : SQL(query) error or missing database.
    	(no such table: matched_contacts (code 1): , while compiling: SELECT id, report_date, known_case_id FROM matched_contacts ORDER BY id)
    #################################################################
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1008)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:573)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:59)
        at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
        at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
        at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1707)
        at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1554)
        at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1425)
        at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1593)
        at org.dpppt.android.sdk.internal.database.Database.getMatchedContacts(Database.java:213)
        at org.dpppt.android.sdk.DP3T.getStatus(DP3T.java:129)
        at org.dpppt.android.calibration.controls.ControlsFragment.updateSdkStatus(ControlsFragment.java:315)
        at org.dpppt.android.calibration.controls.ControlsFragment.onResume(ControlsFragment.java:121)
        at androidx.fragment.app.Fragment.performResume(Fragment.java:2747)
        at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:373)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2625)
        at androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:2589)
        at androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:269)
        at androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:478)
        at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:467)
        at androidx.appcompat.app.AppCompatActivity.onPostResume(AppCompatActivity.java:195)
        at android.app.Activity.performResume(Activity.java:7112)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3768)
        	... 10 more


```

**Comment by Vanuan** [comment]
It looks like database was not initialized.

Several theories:
1. database initialization takes time and DP3T initializes database asynchronously
2. database initialization wasn't executed because DP3T doesn't initialize database if package name doesn't match the process name
3. there are some initialization differences depending on smartphone settings

Are you able to debug the app? Does it crash consistently?

**Comment by cpepi001** [comment]
Yes, and it crash consistently.

**Comment by simonroesch** [comment]
Can you try to clear the data of the app and see if the crash still occurs?

**Comment by cpepi001** [comment]
Now it's working
